name: ecub_s1_v2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  google_nav_bar: ^5.0.6
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  twilio_flutter: ^0.9.0
  google_maps_flutter: ^2.9.0
  
  google_fonts: ^6.2.1
  speech_to_text: ^6.6.0
  tflite_flutter: ^0.11.0
  slide_to_act: ^2.0.2
  razorpay_flutter: ^1.3.7
  flutter_svg: ^1.0.3
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  translator: ^1.0.0
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  location: ^6.0.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
    - assets/foods/
    - assets/ml_models/
