// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEf2mLsMWEosjq3OrjGOcOKWifGmLzelM',
    appId: '1:214420805388:web:46c51e24fd1ea47115db29',
    messagingSenderId: '214420805388',
    projectId: 'ecub-v2',
    authDomain: 'ecub-v2.firebaseapp.com',
    storageBucket: 'ecub-v2.appspot.com',
    measurementId: 'G-86JX881R23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LIOUG9e0jevUPj78I-BnPW6G7wd4Ymo',
    appId: '1:214420805388:android:f1c383e99b121e5015db29',
    messagingSenderId: '214420805388',
    projectId: 'ecub-v2',
    storageBucket: 'ecub-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ARSZ-N-goKK1ouLOFaU1asesUsTFohg',
    appId: '1:214420805388:ios:10dff23db787318115db29',
    messagingSenderId: '214420805388',
    projectId: 'ecub-v2',
    storageBucket: 'ecub-v2.appspot.com',
    androidClientId: '214420805388-476ro9sto1snq2pkv22ce08v5f45an97.apps.googleusercontent.com',
    iosClientId: '214420805388-pvcavjeb5jf1pouvkg8fa6dck99nf5u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecubS1V2',
  );

}